/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,jsx}",
  ],
  theme: {
    extend: {
      colors: {
        'surface': '#131313',
        'surface-dim': '#131313',
        'surface-bright': '#393939',
        'surface-container-lowest': '#0e0e0e',
        'surface-container-low': '#1b1c1c',
        'surface-container': '#1f2020',
        'surface-container-high': '#2a2a2a',
        'surface-container-highest': '#353535',
        'surface-variant': '#353535',
        'on-surface': '#e4e2e1',
        'on-surface-variant': '#c4c7c7',
        'outline': '#8e9192',
        'outline-variant': '#444748',
        'primary': '#c8c6c5',
        'on-primary': '#313030',
        'secondary': '#ffb59e',
        'on-secondary': '#5e1700',
        'secondary-container': '#ff571a',
        'on-secondary-container': '#521300',
        'secondary-fixed': '#ffdbd0',
        'on-secondary-fixed': '#3a0b00',
        'tertiary': '#c6c6c7',
        'on-tertiary': '#2f3131',
        'tertiary-container': '#101212',
        'error': '#ffb4ab',
        'on-error': '#690005',
        'error-container': '#93000a',
        'on-error-container': '#ffdad6',
        'background': '#131313',
        'on-background': '#e4e2e1',
      },
      fontFamily: {
        'display': ['Montserrat', 'sans-serif'],
        'body': ['Inter', 'sans-serif'],
      },
      fontSize: {
        'display-lg': ['64px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '900' }],
        'headline-xl': ['48px', { lineHeight: '1.2', fontWeight: '800' }],
        'headline-lg': ['32px', { lineHeight: '1.2', fontWeight: '700' }],
        'headline-lg-mobile': ['28px', { lineHeight: '1.2', fontWeight: '700' }],
        'title-md': ['20px', { lineHeight: '1.4', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'label-bold': ['14px', { lineHeight: '1.2', fontWeight: '700' }],
        'caption': ['12px', { lineHeight: '1.4', fontWeight: '500' }],
      },
      spacing: {
        'stack-sm': '8px',
        'stack-md': '16px',
        'stack-lg': '32px',
        'section-gap': '80px',
        'container-margin': '24px',
        'gutter': '16px',
      },
      borderRadius: {
        'sm': '0.25rem',
        'DEFAULT': '0.5rem',
        'md': '0.75rem',
        'lg': '1rem',
        'xl': '1.5rem',
        'full': '9999px',
      },
      boxShadow: {
        'ambient': '0 8px 32px rgba(0,0,0,0.4)',
        'ambient-lg': '0 16px 48px rgba(0,0,0,0.6)',
        'glow': '0 0 24px rgba(255,87,26,0.3)',
        'glow-lg': '0 8px 24px rgba(255,87,26,0.25)',
      },
      backgroundImage: {
        'gradient-hero': 'linear-gradient(to top, #131313 0%, rgba(19,19,19,0.4) 50%, transparent 100%)',
      },
    },
  },
  plugins: [],
}
